[package]
name = "sink_meilisearch"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
meilisearch-sdk = "0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
async-trait = "0.1.89"
