[package]
name = "sink_meilisearch"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
meilisearch-sdk = "0.30.0"
serde_json = "1.0"
futures-io = "0.3.31"
tokio = "1.48.0"
tracing = "0.1"
