[workspace]
members = ["source","source/source_mysql", "sink", "common"]

[package]
name = "rust_cdc_hub"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "common" }
source = { path = "source" }
source_mysql = { path = "source/source_mysql" }
sink = { path = "sink" }
tokio = "1.48.0"
serde_yaml = "0.9.34+deprecated"
serde_json = "1.0.145"
