[package]
name = "source_mysql"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql-binlog-connector-rust = "0.3.3"
tokio = { version = "1", features = ["full"] }
common = { path = "../../common" }
async-trait = "0.1.89"
#sea-orm = { version = "1.1", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
sqlx = { version = "0.8", default-features = false, features = ["mysql", "tls-rustls", "runtime-tokio", "sqlx-macros"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1"
