[package]
name = "source_mysql"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql-binlog-connector-rust = "0.3.3"
tokio = { version = "1", features = ["full"] }
common = { path = "../../common" }
async-trait = "0.1.89"
dotenv = "0.15.0"
