[package]
name = "sink_print"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
async-trait = "0.1.89"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
