[package]
name = "source"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
source_mysql = { path = "source_mysql" }
tokio = { version = "1", features = ["full"] }
log = "0.4.29"
